# Generated by Django 5.0.7 on 2024-08-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=10000)),
                ('short_url', models.URLField(max_length=10000)),
                ('valid_upto', models.DateTimeField()),
            ],
        ),
    ]
