# Generated by Django 5.0.7 on 2024-08-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_db',
            name='short_url',
            field=models.URLField(max_length=10, unique=True),
        ),
    ]
