# Generated by Django 5.0.7 on 2024-08-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_alter_url_db_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_db',
            name='short_url',
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
