# Generated by Django 5.0.7 on 2024-08-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0003_alter_url_db_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_db',
            name='valid_upto',
            field=models.DateField(),
        ),
    ]
