# Generated by Django 5.0.7 on 2024-08-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0004_alter_url_db_valid_upto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_db',
            name='valid_upto',
            field=models.TextField(),
        ),
    ]
